# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import substate_pb2 as substate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstate.proto\x12\x05state\x1a\x0esubstate.proto\"\xa4\x01\n\x05State\x12+\n\x08internal\x18\x01 \x01(\x0b\x32\x14.state.StateInternalH\x00\x88\x01\x01\x12\'\n\tinherited\x18\x02 \x01(\x0b\x32\x0f.substate.StateH\x01\x88\x01\x01\x12\x19\n\x0cglobal_param\x18\x03 \x01(\rH\x02\x88\x01\x01\x42\x0b\n\t_internalB\x0c\n\n_inheritedB\x0f\n\r_global_param\"\x1f\n\rStateInternal\x12\x0e\n\x06param1\x18\x01 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'state_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATE._serialized_start=39
  _STATE._serialized_end=203
  _STATEINTERNAL._serialized_start=205
  _STATEINTERNAL._serialized_end=236
# @@protoc_insertion_point(module_scope)
