# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: substate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esubstate.proto\x12\x08substate\"S\n\x05State\x12\x13\n\x06param1\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x19\n\x0cprint_param1\x18\x02 \x01(\x08H\x01\x88\x01\x01\x42\t\n\x07_param1B\x0f\n\r_print_param1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'substate_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATE._serialized_start=28
  _STATE._serialized_end=111
# @@protoc_insertion_point(module_scope)
