// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExampleMessage {
    #[prost(string, tag = "1")]
    pub content: ::prost::alloc::string::String,
}
